Feature/filter
reald002/todolist-react pull request #3
Opened 2021-06-18 11:20 UTC by reald002

2021-06-18 12:55 UTC, IslamRustamov1 commented
resolve conflicts please

2021-06-18 12:57 UTC, IslamRustamov1 commented on src/components/Filters/index.js
> +                {props.data.filter(e => !e.checked).length > 0 ? `${props.data?.filter(e => !e.checked).length} item${props.data?.filter(e => !e.checked).length > 1 ? 's' : ''} left` : ''}
3 repetitive filters in one line

2021-06-18 13:09 UTC, IslamRustamov1 commented on src/components/Filters/index.js
> +        const value = e.target.value === 'Active' ? false : e.target.value === 'Completed' ? true : e.target.value;
Try to avoid this kind of multiple ternary operators. Better to rewrite it with if else.

2021-06-18 14:26 UTC, IslamRustamov1 approved these changes

2021-06-18 16:34 UTC, AnnaKulkova requested changes

2021-06-18 16:34 UTC, AnnaKulkova commented on src/App.js
> +        const newObj = Object.assign(this.state.data.find(e => e.id === id));
You'll get an error if **find** returns **undefind**.

And don't use assign to copy object, use spread operator instead.

2021-06-18 16:34 UTC, AnnaKulkova commented on src/App.js
> +        const todos = this.checkbox.current.children;
You have to use state, not refs. You avoid react philosophy

2021-06-18 16:34 UTC, AnnaKulkova commented on src/components/Filters/filter-btn.js
> +            <input defaultChecked={id === 0 ? 'checked': ''} id={`filter-${id}`} value={text} className="filter-radio" name="filter-radio" type="radio"/>
What do you mean by `id === 0`?

2021-06-18 16:34 UTC, AnnaKulkova commented on src/components/Filters/index.js
> +            <div onChange={handleRadioChange} className="filter-buttons filters__item">
Are you sure that you want to pass it into div? Not in Button?

2021-06-18 16:34 UTC, AnnaKulkova commented on src/components/Filters/index.js
> +        switch(e.target.value) {
Again, use state, not target

2021-06-18 16:34 UTC, AnnaKulkova commented on src/components/TodoItem/index.js
> +            <li style={{ display: (this.props.filter === this.props.checked || this.props.filter === 'All') ? 'flex' : 'none' }}  className="todo-item">
Use Conditional Rendering for it

2021-06-21 08:47 UTC, AnnaKulkova approved these changes
Not ideal but much better now. Merge when ready

2021-06-21 08:48 UTC, merged